###
GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/blogs/10


###
POST http://localhost:3003/api/blogs/
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld1VzZXJuYW1lIiwiaWQiOjEsImlhdCI6MTcyNTcyMTEyOH0._ZrRLZBEOmM0HGsGzdRFs1R2DdVytkwCYT7j4YAteBg

{
    "author": "example 1",
    "url": "url.com",
    "title": "title 1",
    "likes": 19999
}

###
DELETE  http://localhost:3003/api/blogs/6
content-type: application/json

{
    "author": "author from rest",
    "url": "url.com",
    "title": "title from rest",
    "likes": 7
}

###
PUT http://localhost:3003/api/blogs/7
content-type: application/json

{
   
    "likes": 3
}
###
GET  http://localhost:3003/api/users/



###
POST http://localhost:3003/api/users/
content-type: application/json

{
    "username": "nab",
    "name": "nabina"
}

###
PUT  http://localhost:3003/api/users/nab
content-type: application/json

{
    "username": "newUsername"
    
}
###
POST http://localhost:3003/api/login/
content-type: application/json

{
    "username": "newUsername",
    "password": "secret"
   
}
