###
GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/blogs/6
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hYmluYTNAZ21haWwuY29tIiwiaWQiOjMsImlhdCI6MTcyNzAwNTg3Nn0.UoKLfC5CaVDk1Zk0R5qdbrDy0BWOAtvTf9uFJ1UG7mw



###
POST http://localhost:3003/api/blogs/
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hYmluYTJAZ21haWwuY29tIiwiaWQiOjIsImlhdCI6MTcyNzAwNzI2MH0.WMn5TEn7DIX5cngsGiGKtaBnWmgRGEWONSbHQyJ4vAk

{
    "author": "author 10",
    "url": "url.com",
    "title": "title example ",
    "likes": 234,
    "year":2012
    
}

###
DELETE  http://localhost:3003/api/blogs/9
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hYmluYTNAZ21haWwuY29tIiwiaWQiOjMsImlhdCI6MTcyNzAwNTg3Nn0.UoKLfC5CaVDk1Zk0R5qdbrDy0BWOAtvTf9uFJ1UG7mk


###
PUT http://localhost:3003/api/blogs/7
content-type: application/json

{
   
    "likes": 3
}
###
GET  http://localhost:3003/api/users/



###
POST http://localhost:3003/api/users/
content-type: application/json

{
    "username": "nabina6@gmail.com",
    "name": "nabina6"
}

###
PUT  http://localhost:3003/api/users/nabina@gmail.com
content-type: application/json

{
    "username": "newName@gmail.com"
    
}
###
POST http://localhost:3003/api/login/
content-type: application/json

{
    "username": "nabina3@gmail.com",
    "password": "secret"
   
}
###
DELETE  http://localhost:3003/api/logout
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hYmluYTNAZ21haWwuY29tIiwiaWQiOjMsImlhdCI6MTcyNzAxMDM3OH0.tlrXKF0-shE60xsAS-PbKyo7ZQtaXtnDeXcPI1Ut-NI




###
POST http://localhost:3003/api/reading-lists
content-type: application/json


  {
  "userId": 3,
  "blogId": 5
}

###
PUT http://localhost:3003/api/reading-lists/3
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hYmluYTNAZ21haWwuY29tIiwiaWQiOjMsImlhdCI6MTcyNjg0NDE3OX0.-9iTRiSZbXy09IUSmU7AUWvWHRmjw8o4GfQtFdF-agU

{
    "read":true
    
}


