###
GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/blogs/10


###
POST http://localhost:3003/api/blogs/
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld1VzZXJuYW1lQGdtYWlsLmNvbSIsImlkIjozLCJpYXQiOjE3MjU3OTczODB9.o54otllpzK5Sx9hpbWEOmMi0SkaXIxQkGZeA9BFZD4k

{
    "author": "example 2 fro deleting",
    "url": "url.com",
    "title": "title 2",
    "likes": 37643
}

###
DELETE  http://localhost:3003/api/blogs/12
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld1VzZXJuYW1lQGdtYWlsLmNvbSIsImlkIjozLCJpYXQiOjE3MjU3OTc1ODJ9.92_p6KlG05kOKsy97cBTspwNx5u501eEu_nNUjNBOvY


###
PUT http://localhost:3003/api/blogs/7
content-type: application/json

{
   
    "likes": 3
}
###
GET  http://localhost:3003/api/users/



###
POST http://localhost:3003/api/users/
content-type: application/json

{
    "username": "nabina@gmail.com",
    "name": "nabina"
}

###
PUT  http://localhost:3003/api/users/nabina@gmail.com
content-type: application/json

{
    "username": "newName@gmail.com"
    
}
###
POST http://localhost:3003/api/login/
content-type: application/json

{
    "username": "newUsername@gmail.com",
    "password": "secret"
   
}

